# Generated by Django 4.2.20 on 2025-03-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_organization_admin',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
