# Generated by Django 4.2.20 on 2025-03-18 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription_plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription_plans.subscriptionplan')),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='organizatio_id_66521e_idx'), models.Index(fields=['name'], name='organizatio_name_537540_idx')],
            },
        ),
    ]
