# Generated by Django 4.2.20 on 2025-03-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_assigned_user_task_assigned_users'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_status_4a0a95_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['title'], name='tasks_task_title_6b13c2_idx'),
        ),
    ]
