# Generated by Django 4.2.20 on 2025-03-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_users', models.PositiveIntegerField()),
                ('features', models.TextField()),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='subscriptio_id_03b312_idx'), models.Index(fields=['name'], name='subscriptio_name_9c85ac_idx')],
            },
        ),
    ]
